# fly.toml app configuration file generated for fso-phonebook-exercise on 2023-08-19T00:46:36+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fso-phonebook-exercise"
primary_region = "iad"

[build]

[env]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
